# action.yml
name: 'Terratest'
description: 'Container that can run terratest'
inputs:
  tf_actions_version:
    description: 'Terraform version to install.'
    required: true
  tf_actions_comment:
    description: 'Whether or not to comment on pull requests.'
    default: true
  tf_actions_working_dir:
    description: 'Where to locate test-files for terratest.'
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
